### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token: EmainesToken
x-key: EmainesKey
### Verbo GET – listar um
GET http://localhost:8000/funcionario/10 HTTP/1.1
x-token: EmainesToken
x-key: EmainesKey
### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
x-token: EmainesToken
x-key: EmainesKey
content-type: application/json

{
"nome" : "Abc da Silva",
"cpf" : "000.000.000-00",
"telefone" : "(49) 988234567",
"senha" : "bolinhas",
"matricula" : "12345",
"grupo" : 3
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token: EmainesToken
x-key: EmainesKey
content-type: application/json

{
"nome" : "Abc da Silva",
"cpf" : "000.000.000-00",
"telefone" : "(49) 988234567",
"senha" : "1d6442ddcfd9db1ff81df77cbefcd5afcc8c7ca952ab3101ede17a84b866d3f3",
"matricula" : "12345",
"grupo" : 3
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/3 HTTP/1.1
x-token: EmainesToken
x-key: EmainesKey